1,customize,tInfoExportGroup,FULL,6,"PRINT N'===== FULL: customize.tInfoExportGroup (6 rows) ====='; SELECT N'customize.tInfoExportGroup' AS [__SourceTable], * FROM [customize].[tInfoExportGroup];"
2,customize,tInfoExportGroupDetail,FULL,87,"PRINT N'===== FULL: customize.tInfoExportGroupDetail (87 rows) ====='; SELECT N'customize.tInfoExportGroupDetail' AS [__SourceTable], * FROM [customize].[tInfoExportGroupDetail];"
3,customize,tLog_Tranfersite,SAMPLE,4070,"PRINT N'===== SAMPLE: customize.tLog_Tranfersite (TOP 100 of 4070) ====='; SELECT TOP (100) N'customize.tLog_Tranfersite' AS [__SourceTable], * FROM [customize].[tLog_Tranfersite];"
4,customize,tMOD_LogSetting,FULL,179,"PRINT N'===== FULL: customize.tMOD_LogSetting (179 rows) ====='; SELECT N'customize.tMOD_LogSetting' AS [__SourceTable], * FROM [customize].[tMOD_LogSetting];"
5,customize,tSCC_AprvSite,FULL,141,"PRINT N'===== FULL: customize.tSCC_AprvSite (141 rows) ====='; SELECT N'customize.tSCC_AprvSite' AS [__SourceTable], * FROM [customize].[tSCC_AprvSite];"
6,customize,tSCC_PayAllowance,SAMPLE,5057,"PRINT N'===== SAMPLE: customize.tSCC_PayAllowance (TOP 100 of 5057) ====='; SELECT TOP (100) N'customize.tSCC_PayAllowance' AS [__SourceTable], * FROM [customize].[tSCC_PayAllowance];"
7,customize,tSCC_PaySelectPeriod,FULL,2,"PRINT N'===== FULL: customize.tSCC_PaySelectPeriod (2 rows) ====='; SELECT N'customize.tSCC_PaySelectPeriod' AS [__SourceTable], * FROM [customize].[tSCC_PaySelectPeriod];"
8,customize,tSCC_SelectFilter,SAMPLE,6647,"PRINT N'===== SAMPLE: customize.tSCC_SelectFilter (TOP 100 of 6647) ====='; SELECT TOP (100) N'customize.tSCC_SelectFilter' AS [__SourceTable], * FROM [customize].[tSCC_SelectFilter];"
9,customize,tSCC_SettingIncentive,SAMPLE,3400,"PRINT N'===== SAMPLE: customize.tSCC_SettingIncentive (TOP 100 of 3400) ====='; SELECT TOP (100) N'customize.tSCC_SettingIncentive' AS [__SourceTable], * FROM [customize].[tSCC_SettingIncentive];"
10,customize,tSCC_SettingPayAllowance,FULL,2,"PRINT N'===== FULL: customize.tSCC_SettingPayAllowance (2 rows) ====='; SELECT N'customize.tSCC_SettingPayAllowance' AS [__SourceTable], * FROM [customize].[tSCC_SettingPayAllowance];"
11,customize,tSCC_TempApproveEmail,FULL,26,"PRINT N'===== FULL: customize.tSCC_TempApproveEmail (26 rows) ====='; SELECT N'customize.tSCC_TempApproveEmail' AS [__SourceTable], * FROM [customize].[tSCC_TempApproveEmail];"
12,customize,tSCC_TranferApprove,SAMPLE,10657,"PRINT N'===== SAMPLE: customize.tSCC_TranferApprove (TOP 100 of 10657) ====='; SELECT TOP (100) N'customize.tSCC_TranferApprove' AS [__SourceTable], * FROM [customize].[tSCC_TranferApprove];"
13,customize,tSCC_TranferEmp,SAMPLE,10657,"PRINT N'===== SAMPLE: customize.tSCC_TranferEmp (TOP 100 of 10657) ====='; SELECT TOP (100) N'customize.tSCC_TranferEmp' AS [__SourceTable], * FROM [customize].[tSCC_TranferEmp];"
14,customize,tSCC_TranferSite,SAMPLE,10657,"PRINT N'===== SAMPLE: customize.tSCC_TranferSite (TOP 100 of 10657) ====='; SELECT TOP (100) N'customize.tSCC_TranferSite' AS [__SourceTable], * FROM [customize].[tSCC_TranferSite];"
15,dbo,__MigrationHistory,FULL,1,"PRINT N'===== FULL: dbo.__MigrationHistory (1 rows) ====='; SELECT N'dbo.__MigrationHistory' AS [__SourceTable], * FROM [dbo].[__MigrationHistory];"
16,dbo,_DBMigrationHistory,SAMPLE,2825,"PRINT N'===== SAMPLE: dbo._DBMigrationHistory (TOP 100 of 2825) ====='; SELECT TOP (100) N'dbo._DBMigrationHistory' AS [__SourceTable], * FROM [dbo].[_DBMigrationHistory];"
17,dbo,_DBTicketLg,FULL,84,"PRINT N'===== FULL: dbo._DBTicketLg (84 rows) ====='; SELECT N'dbo._DBTicketLg' AS [__SourceTable], * FROM [dbo].[_DBTicketLg];"
18,dbo,sysdiagrams,FULL,3,"PRINT N'===== FULL: dbo.sysdiagrams (3 rows) ====='; SELECT N'dbo.sysdiagrams' AS [__SourceTable], * FROM [dbo].[sysdiagrams];"
19,dbo,tAppConnector,FULL,1,"PRINT N'===== FULL: dbo.tAppConnector (1 rows) ====='; SELECT N'dbo.tAppConnector' AS [__SourceTable], * FROM [dbo].[tAppConnector];"
20,dbo,tApproverList,FULL,24,"PRINT N'===== FULL: dbo.tApproverList (24 rows) ====='; SELECT N'dbo.tApproverList' AS [__SourceTable], * FROM [dbo].[tApproverList];"
21,dbo,tAssignMenuPermission,FULL,3,"PRINT N'===== FULL: dbo.tAssignMenuPermission (3 rows) ====='; SELECT N'dbo.tAssignMenuPermission' AS [__SourceTable], * FROM [dbo].[tAssignMenuPermission];"
22,dbo,tAssignUserRole,FULL,10,"PRINT N'===== FULL: dbo.tAssignUserRole (10 rows) ====='; SELECT N'dbo.tAssignUserRole' AS [__SourceTable], * FROM [dbo].[tAssignUserRole];"
23,dbo,tAssignWorkCalendar,FULL,1,"PRINT N'===== FULL: dbo.tAssignWorkCalendar (1 rows) ====='; SELECT N'dbo.tAssignWorkCalendar' AS [__SourceTable], * FROM [dbo].[tAssignWorkCalendar];"
24,dbo,tAutoGenID,FULL,1,"PRINT N'===== FULL: dbo.tAutoGenID (1 rows) ====='; SELECT N'dbo.tAutoGenID' AS [__SourceTable], * FROM [dbo].[tAutoGenID];"
25,dbo,tAutoPushTime_Tran_Manual,SAMPLE,52346,"PRINT N'===== SAMPLE: dbo.tAutoPushTime_Tran_Manual (TOP 100 of 52346) ====='; SELECT TOP (100) N'dbo.tAutoPushTime_Tran_Manual' AS [__SourceTable], * FROM [dbo].[tAutoPushTime_Tran_Manual];"
26,dbo,tAward_Type,FULL,1,"PRINT N'===== FULL: dbo.tAward_Type (1 rows) ====='; SELECT N'dbo.tAward_Type' AS [__SourceTable], * FROM [dbo].[tAward_Type];"
27,dbo,tBadgeStyle,FULL,1,"PRINT N'===== FULL: dbo.tBadgeStyle (1 rows) ====='; SELECT N'dbo.tBadgeStyle' AS [__SourceTable], * FROM [dbo].[tBadgeStyle];"
28,dbo,tBankMaster,FULL,56,"PRINT N'===== FULL: dbo.tBankMaster (56 rows) ====='; SELECT N'dbo.tBankMaster' AS [__SourceTable], * FROM [dbo].[tBankMaster];"
29,dbo,tBankName,FULL,36,"PRINT N'===== FULL: dbo.tBankName (36 rows) ====='; SELECT N'dbo.tBankName' AS [__SourceTable], * FROM [dbo].[tBankName];"
30,dbo,tBatchAdjust,FULL,4,"PRINT N'===== FULL: dbo.tBatchAdjust (4 rows) ====='; SELECT N'dbo.tBatchAdjust' AS [__SourceTable], * FROM [dbo].[tBatchAdjust];"
31,dbo,tBatchLeave,FULL,1,"PRINT N'===== FULL: dbo.tBatchLeave (1 rows) ====='; SELECT N'dbo.tBatchLeave' AS [__SourceTable], * FROM [dbo].[tBatchLeave];"
32,dbo,tBatchProbation,FULL,1,"PRINT N'===== FULL: dbo.tBatchProbation (1 rows) ====='; SELECT N'dbo.tBatchProbation' AS [__SourceTable], * FROM [dbo].[tBatchProbation];"
33,dbo,tBatchResign,FULL,1,"PRINT N'===== FULL: dbo.tBatchResign (1 rows) ====='; SELECT N'dbo.tBatchResign' AS [__SourceTable], * FROM [dbo].[tBatchResign];"
34,dbo,tBillChargeRate,FULL,1,"PRINT N'===== FULL: dbo.tBillChargeRate (1 rows) ====='; SELECT N'dbo.tBillChargeRate' AS [__SourceTable], * FROM [dbo].[tBillChargeRate];"
35,dbo,tBU_FieldCaption,FULL,1,"PRINT N'===== FULL: dbo.tBU_FieldCaption (1 rows) ====='; SELECT N'dbo.tBU_FieldCaption' AS [__SourceTable], * FROM [dbo].[tBU_FieldCaption];"
36,dbo,tBU1,SAMPLE,532,"PRINT N'===== SAMPLE: dbo.tBU1 (TOP 100 of 532) ====='; SELECT TOP (100) N'dbo.tBU1' AS [__SourceTable], * FROM [dbo].[tBU1];"
37,dbo,tBU1_New,SAMPLE,560,"PRINT N'===== SAMPLE: dbo.tBU1_New (TOP 100 of 560) ====='; SELECT TOP (100) N'dbo.tBU1_New' AS [__SourceTable], * FROM [dbo].[tBU1_New];"
38,dbo,tBU2,FULL,4,"PRINT N'===== FULL: dbo.tBU2 (4 rows) ====='; SELECT N'dbo.tBU2' AS [__SourceTable], * FROM [dbo].[tBU2];"
39,dbo,tBU2_New,FULL,13,"PRINT N'===== FULL: dbo.tBU2_New (13 rows) ====='; SELECT N'dbo.tBU2_New' AS [__SourceTable], * FROM [dbo].[tBU2_New];"
40,dbo,tBU3,FULL,1,"PRINT N'===== FULL: dbo.tBU3 (1 rows) ====='; SELECT N'dbo.tBU3' AS [__SourceTable], * FROM [dbo].[tBU3];"
41,dbo,tBU3_New,FULL,1,"PRINT N'===== FULL: dbo.tBU3_New (1 rows) ====='; SELECT N'dbo.tBU3_New' AS [__SourceTable], * FROM [dbo].[tBU3_New];"
42,dbo,tBU4,FULL,1,"PRINT N'===== FULL: dbo.tBU4 (1 rows) ====='; SELECT N'dbo.tBU4' AS [__SourceTable], * FROM [dbo].[tBU4];"
43,dbo,tBU4_New,FULL,1,"PRINT N'===== FULL: dbo.tBU4_New (1 rows) ====='; SELECT N'dbo.tBU4_New' AS [__SourceTable], * FROM [dbo].[tBU4_New];"
44,dbo,tCalendarYear,FULL,3,"PRINT N'===== FULL: dbo.tCalendarYear (3 rows) ====='; SELECT N'dbo.tCalendarYear' AS [__SourceTable], * FROM [dbo].[tCalendarYear];"
45,dbo,tCardStatus_Type,FULL,4,"PRINT N'===== FULL: dbo.tCardStatus_Type (4 rows) ====='; SELECT N'dbo.tCardStatus_Type' AS [__SourceTable], * FROM [dbo].[tCardStatus_Type];"
46,dbo,tCertificationStyle,FULL,2,"PRINT N'===== FULL: dbo.tCertificationStyle (2 rows) ====='; SELECT N'dbo.tCertificationStyle' AS [__SourceTable], * FROM [dbo].[tCertificationStyle];"
47,dbo,tChangeset,SAMPLE,734,"PRINT N'===== SAMPLE: dbo.tChangeset (TOP 100 of 734) ====='; SELECT TOP (100) N'dbo.tChangeset' AS [__SourceTable], * FROM [dbo].[tChangeset];"
48,dbo,tChildren_Prefix,FULL,5,"PRINT N'===== FULL: dbo.tChildren_Prefix (5 rows) ====='; SELECT N'dbo.tChildren_Prefix' AS [__SourceTable], * FROM [dbo].[tChildren_Prefix];"
49,dbo,tColDef_PayrollExport,SAMPLE,1584,"PRINT N'===== SAMPLE: dbo.tColDef_PayrollExport (TOP 100 of 1584) ====='; SELECT TOP (100) N'dbo.tColDef_PayrollExport' AS [__SourceTable], * FROM [dbo].[tColDef_PayrollExport];"
50,dbo,tColDef_PayrollFormat,FULL,6,"PRINT N'===== FULL: dbo.tColDef_PayrollFormat (6 rows) ====='; SELECT N'dbo.tColDef_PayrollFormat' AS [__SourceTable], * FROM [dbo].[tColDef_PayrollFormat];"
51,dbo,tColDef_rEmployeeExport,FULL,167,"PRINT N'===== FULL: dbo.tColDef_rEmployeeExport (167 rows) ====='; SELECT N'dbo.tColDef_rEmployeeExport' AS [__SourceTable], * FROM [dbo].[tColDef_rEmployeeExport];"
52,dbo,tColDef_rEmployeeExportNew,SAMPLE,871,"PRINT N'===== SAMPLE: dbo.tColDef_rEmployeeExportNew (TOP 100 of 871) ====='; SELECT TOP (100) N'dbo.tColDef_rEmployeeExportNew' AS [__SourceTable], * FROM [dbo].[tColDef_rEmployeeExportNew];"
53,dbo,tCompany,FULL,3,"PRINT N'===== FULL: dbo.tCompany (3 rows) ====='; SELECT N'dbo.tCompany' AS [__SourceTable], * FROM [dbo].[tCompany];"
54,dbo,tControlMOD,FULL,2,"PRINT N'===== FULL: dbo.tControlMOD (2 rows) ====='; SELECT N'dbo.tControlMOD' AS [__SourceTable], * FROM [dbo].[tControlMOD];"
55,dbo,tCostCenter,FULL,3,"PRINT N'===== FULL: dbo.tCostCenter (3 rows) ====='; SELECT N'dbo.tCostCenter' AS [__SourceTable], * FROM [dbo].[tCostCenter];"
56,dbo,tData_PND1_Detail,FULL,3,"PRINT N'===== FULL: dbo.tData_PND1_Detail (3 rows) ====='; SELECT N'dbo.tData_PND1_Detail' AS [__SourceTable], * FROM [dbo].[tData_PND1_Detail];"
57,dbo,tDecoration,FULL,1,"PRINT N'===== FULL: dbo.tDecoration (1 rows) ====='; SELECT N'dbo.tDecoration' AS [__SourceTable], * FROM [dbo].[tDecoration];"
58,dbo,tDecorationGroup,FULL,5,"PRINT N'===== FULL: dbo.tDecorationGroup (5 rows) ====='; SELECT N'dbo.tDecorationGroup' AS [__SourceTable], * FROM [dbo].[tDecorationGroup];"
59,dbo,tEmployee,SAMPLE,21939,"PRINT N'===== SAMPLE: dbo.tEmployee (TOP 100 of 21939) ====='; SELECT TOP (100) N'dbo.tEmployee' AS [__SourceTable], * FROM [dbo].[tEmployee];"
60,dbo,tEmployee_Children,FULL,10,"PRINT N'===== FULL: dbo.tEmployee_Children (10 rows) ====='; SELECT N'dbo.tEmployee_Children' AS [__SourceTable], * FROM [dbo].[tEmployee_Children];"
61,dbo,tEmployee_FieldCaption,FULL,1,"PRINT N'===== FULL: dbo.tEmployee_FieldCaption (1 rows) ====='; SELECT N'dbo.tEmployee_FieldCaption' AS [__SourceTable], * FROM [dbo].[tEmployee_FieldCaption];"
62,dbo,tEmployee_LeaveQuota,SAMPLE,12087,"PRINT N'===== SAMPLE: dbo.tEmployee_LeaveQuota (TOP 100 of 12087) ====='; SELECT TOP (100) N'dbo.tEmployee_LeaveQuota' AS [__SourceTable], * FROM [dbo].[tEmployee_LeaveQuota];"
63,dbo,tEmployee_New,SAMPLE,21945,"PRINT N'===== SAMPLE: dbo.tEmployee_New (TOP 100 of 21945) ====='; SELECT TOP (100) N'dbo.tEmployee_New' AS [__SourceTable], * FROM [dbo].[tEmployee_New];"
64,dbo,tEmployee_OtherCard,SAMPLE,2282,"PRINT N'===== SAMPLE: dbo.tEmployee_OtherCard (TOP 100 of 2282) ====='; SELECT TOP (100) N'dbo.tEmployee_OtherCard' AS [__SourceTable], * FROM [dbo].[tEmployee_OtherCard];"
65,dbo,tEmployee_RateP0x,SAMPLE,8773,"PRINT N'===== SAMPLE: dbo.tEmployee_RateP0x (TOP 100 of 8773) ====='; SELECT TOP (100) N'dbo.tEmployee_RateP0x' AS [__SourceTable], * FROM [dbo].[tEmployee_RateP0x];"
66,dbo,tEmployeeAbility,FULL,8,"PRINT N'===== FULL: dbo.tEmployeeAbility (8 rows) ====='; SELECT N'dbo.tEmployeeAbility' AS [__SourceTable], * FROM [dbo].[tEmployeeAbility];"
67,dbo,tEmployeeLevel,FULL,14,"PRINT N'===== FULL: dbo.tEmployeeLevel (14 rows) ====='; SELECT N'dbo.tEmployeeLevel' AS [__SourceTable], * FROM [dbo].[tEmployeeLevel];"
68,dbo,tEmployeeLevel_LeaveType,FULL,12,"PRINT N'===== FULL: dbo.tEmployeeLevel_LeaveType (12 rows) ====='; SELECT N'dbo.tEmployeeLevel_LeaveType' AS [__SourceTable], * FROM [dbo].[tEmployeeLevel_LeaveType];"
69,dbo,tEmployeePhoto,SAMPLE,16440,"PRINT N'===== SAMPLE: dbo.tEmployeePhoto (TOP 100 of 16440) ====='; SELECT TOP (100) N'dbo.tEmployeePhoto' AS [__SourceTable], * FROM [dbo].[tEmployeePhoto];"
70,dbo,tEmployeeStatus,FULL,3,"PRINT N'===== FULL: dbo.tEmployeeStatus (3 rows) ====='; SELECT N'dbo.tEmployeeStatus' AS [__SourceTable], * FROM [dbo].[tEmployeeStatus];"
71,dbo,tEmployeeStatusGroup,FULL,3,"PRINT N'===== FULL: dbo.tEmployeeStatusGroup (3 rows) ====='; SELECT N'dbo.tEmployeeStatusGroup' AS [__SourceTable], * FROM [dbo].[tEmployeeStatusGroup];"
72,dbo,tEmployeeTitle,FULL,209,"PRINT N'===== FULL: dbo.tEmployeeTitle (209 rows) ====='; SELECT N'dbo.tEmployeeTitle' AS [__SourceTable], * FROM [dbo].[tEmployeeTitle];"
73,dbo,tEmployeeType_FieldCaption,FULL,1,"PRINT N'===== FULL: dbo.tEmployeeType_FieldCaption (1 rows) ====='; SELECT N'dbo.tEmployeeType_FieldCaption' AS [__SourceTable], * FROM [dbo].[tEmployeeType_FieldCaption];"
74,dbo,tEmployeeType1,FULL,5,"PRINT N'===== FULL: dbo.tEmployeeType1 (5 rows) ====='; SELECT N'dbo.tEmployeeType1' AS [__SourceTable], * FROM [dbo].[tEmployeeType1];"
75,dbo,tEmployeeType2,FULL,1,"PRINT N'===== FULL: dbo.tEmployeeType2 (1 rows) ====='; SELECT N'dbo.tEmployeeType2' AS [__SourceTable], * FROM [dbo].[tEmployeeType2];"
76,dbo,tEmployeeType3,FULL,2,"PRINT N'===== FULL: dbo.tEmployeeType3 (2 rows) ====='; SELECT N'dbo.tEmployeeType3' AS [__SourceTable], * FROM [dbo].[tEmployeeType3];"
77,dbo,tEmployeeWork_Quota,FULL,22,"PRINT N'===== FULL: dbo.tEmployeeWork_Quota (22 rows) ====='; SELECT N'dbo.tEmployeeWork_Quota' AS [__SourceTable], * FROM [dbo].[tEmployeeWork_Quota];"
78,dbo,tFlagWork,FULL,8,"PRINT N'===== FULL: dbo.tFlagWork (8 rows) ====='; SELECT N'dbo.tFlagWork' AS [__SourceTable], * FROM [dbo].[tFlagWork];"
79,dbo,tFlow,FULL,29,"PRINT N'===== FULL: dbo.tFlow (29 rows) ====='; SELECT N'dbo.tFlow' AS [__SourceTable], * FROM [dbo].[tFlow];"
80,dbo,tFlowPath,FULL,29,"PRINT N'===== FULL: dbo.tFlowPath (29 rows) ====='; SELECT N'dbo.tFlowPath' AS [__SourceTable], * FROM [dbo].[tFlowPath];"
81,dbo,tGender,FULL,3,"PRINT N'===== FULL: dbo.tGender (3 rows) ====='; SELECT N'dbo.tGender' AS [__SourceTable], * FROM [dbo].[tGender];"
82,dbo,tGLAccount_MapField,FULL,96,"PRINT N'===== FULL: dbo.tGLAccount_MapField (96 rows) ====='; SELECT N'dbo.tGLAccount_MapField' AS [__SourceTable], * FROM [dbo].[tGLAccount_MapField];"
83,dbo,tGUILTY_Type,FULL,39,"PRINT N'===== FULL: dbo.tGUILTY_Type (39 rows) ====='; SELECT N'dbo.tGUILTY_Type' AS [__SourceTable], * FROM [dbo].[tGUILTY_Type];"
84,dbo,tImport_Employee_MappingPreset,FULL,9,"PRINT N'===== FULL: dbo.tImport_Employee_MappingPreset (9 rows) ====='; SELECT N'dbo.tImport_Employee_MappingPreset' AS [__SourceTable], * FROM [dbo].[tImport_Employee_MappingPreset];"
85,dbo,tImportPlan,FULL,168,"PRINT N'===== FULL: dbo.tImportPlan (168 rows) ====='; SELECT N'dbo.tImportPlan' AS [__SourceTable], * FROM [dbo].[tImportPlan];"
86,dbo,tImportTime_Mapping,FULL,5,"PRINT N'===== FULL: dbo.tImportTime_Mapping (5 rows) ====='; SELECT N'dbo.tImportTime_Mapping' AS [__SourceTable], * FROM [dbo].[tImportTime_Mapping];"
87,dbo,tL0x_FieldCaption,FULL,1,"PRINT N'===== FULL: dbo.tL0x_FieldCaption (1 rows) ====='; SELECT N'dbo.tL0x_FieldCaption' AS [__SourceTable], * FROM [dbo].[tL0x_FieldCaption];"
88,dbo,tLog_AssignWCD,FULL,1,"PRINT N'===== FULL: dbo.tLog_AssignWCD (1 rows) ====='; SELECT N'dbo.tLog_AssignWCD' AS [__SourceTable], * FROM [dbo].[tLog_AssignWCD];"
89,dbo,tLOG_BU,SAMPLE,1266,"PRINT N'===== SAMPLE: dbo.tLOG_BU (TOP 100 of 1266) ====='; SELECT TOP (100) N'dbo.tLOG_BU' AS [__SourceTable], * FROM [dbo].[tLOG_BU];"
90,dbo,tLOG_BU_KeyName,FULL,12,"PRINT N'===== FULL: dbo.tLOG_BU_KeyName (12 rows) ====='; SELECT N'dbo.tLOG_BU_KeyName' AS [__SourceTable], * FROM [dbo].[tLOG_BU_KeyName];"
91,dbo,tLOG_CloseCarryOption,FULL,16,"PRINT N'===== FULL: dbo.tLOG_CloseCarryOption (16 rows) ====='; SELECT N'dbo.tLOG_CloseCarryOption' AS [__SourceTable], * FROM [dbo].[tLOG_CloseCarryOption];"
92,dbo,tLOG_DeleteEmployee,FULL,86,"PRINT N'===== FULL: dbo.tLOG_DeleteEmployee (86 rows) ====='; SELECT N'dbo.tLOG_DeleteEmployee' AS [__SourceTable], * FROM [dbo].[tLOG_DeleteEmployee];"
93,dbo,tLOG_DeleteImportTime,SAMPLE,3201,"PRINT N'===== SAMPLE: dbo.tLOG_DeleteImportTime (TOP 100 of 3201) ====='; SELECT TOP (100) N'dbo.tLOG_DeleteImportTime' AS [__SourceTable], * FROM [dbo].[tLOG_DeleteImportTime];"
94,dbo,tLOG_EmployeeGUID,SAMPLE,1984978,"PRINT N'===== SAMPLE: dbo.tLOG_EmployeeGUID (TOP 100 of 1984978) ====='; SELECT TOP (100) N'dbo.tLOG_EmployeeGUID' AS [__SourceTable], * FROM [dbo].[tLOG_EmployeeGUID];"
95,dbo,tLOG_EmployeeText,SAMPLE,1077517,"PRINT N'===== SAMPLE: dbo.tLOG_EmployeeText (TOP 100 of 1077517) ====='; SELECT TOP (100) N'dbo.tLOG_EmployeeText' AS [__SourceTable], * FROM [dbo].[tLOG_EmployeeText];"
96,dbo,tLog_ImportPlan,FULL,338,"PRINT N'===== FULL: dbo.tLog_ImportPlan (338 rows) ====='; SELECT N'dbo.tLog_ImportPlan' AS [__SourceTable], * FROM [dbo].[tLog_ImportPlan];"
97,dbo,tLOG_OTApprove,SAMPLE,1235090,"PRINT N'===== SAMPLE: dbo.tLOG_OTApprove (TOP 100 of 1235090) ====='; SELECT TOP (100) N'dbo.tLOG_OTApprove' AS [__SourceTable], * FROM [dbo].[tLOG_OTApprove];"
98,dbo,tLog_OTClaim,SAMPLE,5949,"PRINT N'===== SAMPLE: dbo.tLog_OTClaim (TOP 100 of 5949) ====='; SELECT TOP (100) N'dbo.tLog_OTClaim' AS [__SourceTable], * FROM [dbo].[tLog_OTClaim];"
99,dbo,tLOG_OTClaimApprove,SAMPLE,5973,"PRINT N'===== SAMPLE: dbo.tLOG_OTClaimApprove (TOP 100 of 5973) ====='; SELECT TOP (100) N'dbo.tLOG_OTClaimApprove' AS [__SourceTable], * FROM [dbo].[tLOG_OTClaimApprove];"
100,dbo,tLOG_Payroll,SAMPLE,100072,"PRINT N'===== SAMPLE: dbo.tLOG_Payroll (TOP 100 of 100072) ====='; SELECT TOP (100) N'dbo.tLOG_Payroll' AS [__SourceTable], * FROM [dbo].[tLOG_Payroll];"
101,dbo,tLOG_PDF,FULL,10,"PRINT N'===== FULL: dbo.tLOG_PDF (10 rows) ====='; SELECT N'dbo.tLOG_PDF' AS [__SourceTable], * FROM [dbo].[tLOG_PDF];"
102,dbo,tLog_Request,FULL,3,"PRINT N'===== FULL: dbo.tLog_Request (3 rows) ====='; SELECT N'dbo.tLog_Request' AS [__SourceTable], * FROM [dbo].[tLog_Request];"
103,dbo,tLOG_TimeInOut,SAMPLE,402565,"PRINT N'===== SAMPLE: dbo.tLOG_TimeInOut (TOP 100 of 402565) ====='; SELECT TOP (100) N'dbo.tLOG_TimeInOut' AS [__SourceTable], * FROM [dbo].[tLOG_TimeInOut];"
104,dbo,tLOG_TimeInOutDelete,SAMPLE,2861,"PRINT N'===== SAMPLE: dbo.tLOG_TimeInOutDelete (TOP 100 of 2861) ====='; SELECT TOP (100) N'dbo.tLOG_TimeInOutDelete' AS [__SourceTable], * FROM [dbo].[tLOG_TimeInOutDelete];"
105,dbo,tLOG_Update_Employee,FULL,72,"PRINT N'===== FULL: dbo.tLOG_Update_Employee (72 rows) ====='; SELECT N'dbo.tLOG_Update_Employee' AS [__SourceTable], * FROM [dbo].[tLOG_Update_Employee];"
106,dbo,tLOG_UpdateWork_BU,SAMPLE,5225,"PRINT N'===== SAMPLE: dbo.tLOG_UpdateWork_BU (TOP 100 of 5225) ====='; SELECT TOP (100) N'dbo.tLOG_UpdateWork_BU' AS [__SourceTable], * FROM [dbo].[tLOG_UpdateWork_BU];"
107,dbo,tLOG_UpdateWork_Rate,SAMPLE,2504,"PRINT N'===== SAMPLE: dbo.tLOG_UpdateWork_Rate (TOP 100 of 2504) ====='; SELECT TOP (100) N'dbo.tLOG_UpdateWork_Rate' AS [__SourceTable], * FROM [dbo].[tLOG_UpdateWork_Rate];"
108,dbo,tLOG_UpdateWork_Title,FULL,344,"PRINT N'===== FULL: dbo.tLOG_UpdateWork_Title (344 rows) ====='; SELECT N'dbo.tLOG_UpdateWork_Title' AS [__SourceTable], * FROM [dbo].[tLOG_UpdateWork_Title];"
109,dbo,tLOG_UserLogon_Outpay,SAMPLE,10400,"PRINT N'===== SAMPLE: dbo.tLOG_UserLogon_Outpay (TOP 100 of 10400) ====='; SELECT TOP (100) N'dbo.tLOG_UserLogon_Outpay' AS [__SourceTable], * FROM [dbo].[tLOG_UserLogon_Outpay];"
110,dbo,tLogAddLeaveManagement,SAMPLE,81623,"PRINT N'===== SAMPLE: dbo.tLogAddLeaveManagement (TOP 100 of 81623) ====='; SELECT TOP (100) N'dbo.tLogAddLeaveManagement' AS [__SourceTable], * FROM [dbo].[tLogAddLeaveManagement];"
111,dbo,tLogKeyName,FULL,461,"PRINT N'===== FULL: dbo.tLogKeyName (461 rows) ====='; SELECT N'dbo.tLogKeyName' AS [__SourceTable], * FROM [dbo].[tLogKeyName];"
112,dbo,tLogRequest_OT_Process,FULL,35,"PRINT N'===== FULL: dbo.tLogRequest_OT_Process (35 rows) ====='; SELECT N'dbo.tLogRequest_OT_Process' AS [__SourceTable], * FROM [dbo].[tLogRequest_OT_Process];"
113,dbo,tMail_Config,FULL,1,"PRINT N'===== FULL: dbo.tMail_Config (1 rows) ====='; SELECT N'dbo.tMail_Config' AS [__SourceTable], * FROM [dbo].[tMail_Config];"
114,dbo,tManager_Delegated,FULL,143,"PRINT N'===== FULL: dbo.tManager_Delegated (143 rows) ====='; SELECT N'dbo.tManager_Delegated' AS [__SourceTable], * FROM [dbo].[tManager_Delegated];"
115,dbo,tMartialStatus,FULL,5,"PRINT N'===== FULL: dbo.tMartialStatus (5 rows) ====='; SELECT N'dbo.tMartialStatus' AS [__SourceTable], * FROM [dbo].[tMartialStatus];"
116,dbo,tMenuOutpayPermission,SAMPLE,592,"PRINT N'===== SAMPLE: dbo.tMenuOutpayPermission (TOP 100 of 592) ====='; SELECT TOP (100) N'dbo.tMenuOutpayPermission' AS [__SourceTable], * FROM [dbo].[tMenuOutpayPermission];"
117,dbo,tMODBill,FULL,3,"PRINT N'===== FULL: dbo.tMODBill (3 rows) ====='; SELECT N'dbo.tMODBill' AS [__SourceTable], * FROM [dbo].[tMODBill];"
118,dbo,tNationality,FULL,3,"PRINT N'===== FULL: dbo.tNationality (3 rows) ====='; SELECT N'dbo.tNationality' AS [__SourceTable], * FROM [dbo].[tNationality];"
119,dbo,tOther_FieldCaption,FULL,1,"PRINT N'===== FULL: dbo.tOther_FieldCaption (1 rows) ====='; SELECT N'dbo.tOther_FieldCaption' AS [__SourceTable], * FROM [dbo].[tOther_FieldCaption];"
120,dbo,tOTRequest_Time,FULL,5,"PRINT N'===== FULL: dbo.tOTRequest_Time (5 rows) ====='; SELECT N'dbo.tOTRequest_Time' AS [__SourceTable], * FROM [dbo].[tOTRequest_Time];"
121,dbo,tPayroll,SAMPLE,147616,"PRINT N'===== SAMPLE: dbo.tPayroll (TOP 100 of 147616) ====='; SELECT TOP (100) N'dbo.tPayroll' AS [__SourceTable], * FROM [dbo].[tPayroll];"
122,dbo,tPayroll_Allowance,SAMPLE,147616,"PRINT N'===== SAMPLE: dbo.tPayroll_Allowance (TOP 100 of 147616) ====='; SELECT TOP (100) N'dbo.tPayroll_Allowance' AS [__SourceTable], * FROM [dbo].[tPayroll_Allowance];"
123,dbo,tPayroll_ColDef,SAMPLE,1790,"PRINT N'===== SAMPLE: dbo.tPayroll_ColDef (TOP 100 of 1790) ====='; SELECT TOP (100) N'dbo.tPayroll_ColDef' AS [__SourceTable], * FROM [dbo].[tPayroll_ColDef];"
124,dbo,tPayroll_Detail,SAMPLE,147670,"PRINT N'===== SAMPLE: dbo.tPayroll_Detail (TOP 100 of 147670) ====='; SELECT TOP (100) N'dbo.tPayroll_Detail' AS [__SourceTable], * FROM [dbo].[tPayroll_Detail];"
125,dbo,tPayroll_GLAccNo,FULL,278,"PRINT N'===== FULL: dbo.tPayroll_GLAccNo (278 rows) ====='; SELECT N'dbo.tPayroll_GLAccNo' AS [__SourceTable], * FROM [dbo].[tPayroll_GLAccNo];"
126,dbo,tPayroll_GLAccNoRow,SAMPLE,15290,"PRINT N'===== SAMPLE: dbo.tPayroll_GLAccNoRow (TOP 100 of 15290) ====='; SELECT TOP (100) N'dbo.tPayroll_GLAccNoRow' AS [__SourceTable], * FROM [dbo].[tPayroll_GLAccNoRow];"
127,dbo,tPayroll_Tax,SAMPLE,147619,"PRINT N'===== SAMPLE: dbo.tPayroll_Tax (TOP 100 of 147619) ====='; SELECT TOP (100) N'dbo.tPayroll_Tax' AS [__SourceTable], * FROM [dbo].[tPayroll_Tax];"
128,dbo,tPayroll_Welfare,SAMPLE,88692,"PRINT N'===== SAMPLE: dbo.tPayroll_Welfare (TOP 100 of 88692) ====='; SELECT TOP (100) N'dbo.tPayroll_Welfare' AS [__SourceTable], * FROM [dbo].[tPayroll_Welfare];"
129,dbo,tPENALTY_Type,FULL,5,"PRINT N'===== FULL: dbo.tPENALTY_Type (5 rows) ====='; SELECT N'dbo.tPENALTY_Type' AS [__SourceTable], * FROM [dbo].[tPENALTY_Type];"
130,dbo,tPERFORMANCE_Type,FULL,1,"PRINT N'===== FULL: dbo.tPERFORMANCE_Type (1 rows) ====='; SELECT N'dbo.tPERFORMANCE_Type' AS [__SourceTable], * FROM [dbo].[tPERFORMANCE_Type];"
131,dbo,tPeriod_ChargeRate,FULL,150,"PRINT N'===== FULL: dbo.tPeriod_ChargeRate (150 rows) ====='; SELECT N'dbo.tPeriod_ChargeRate' AS [__SourceTable], * FROM [dbo].[tPeriod_ChargeRate];"
132,dbo,tPMPeriod,FULL,150,"PRINT N'===== FULL: dbo.tPMPeriod (150 rows) ====='; SELECT N'dbo.tPMPeriod' AS [__SourceTable], * FROM [dbo].[tPMPeriod];"
133,dbo,tPrefix,FULL,3,"PRINT N'===== FULL: dbo.tPrefix (3 rows) ====='; SELECT N'dbo.tPrefix' AS [__SourceTable], * FROM [dbo].[tPrefix];"
134,dbo,tPreset_Leave,FULL,1,"PRINT N'===== FULL: dbo.tPreset_Leave (1 rows) ====='; SELECT N'dbo.tPreset_Leave' AS [__SourceTable], * FROM [dbo].[tPreset_Leave];"
135,dbo,tProject,FULL,5,"PRINT N'===== FULL: dbo.tProject (5 rows) ====='; SELECT N'dbo.tProject' AS [__SourceTable], * FROM [dbo].[tProject];"
136,dbo,tProject_GLAccNo,FULL,5,"PRINT N'===== FULL: dbo.tProject_GLAccNo (5 rows) ====='; SELECT N'dbo.tProject_GLAccNo' AS [__SourceTable], * FROM [dbo].[tProject_GLAccNo];"
137,dbo,tProject_GLAccNoRow,FULL,275,"PRINT N'===== FULL: dbo.tProject_GLAccNoRow (275 rows) ====='; SELECT N'dbo.tProject_GLAccNoRow' AS [__SourceTable], * FROM [dbo].[tProject_GLAccNoRow];"
138,dbo,tProject_Tax,FULL,5,"PRINT N'===== FULL: dbo.tProject_Tax (5 rows) ====='; SELECT N'dbo.tProject_Tax' AS [__SourceTable], * FROM [dbo].[tProject_Tax];"
139,dbo,tProjectChargeRate,FULL,5,"PRINT N'===== FULL: dbo.tProjectChargeRate (5 rows) ====='; SELECT N'dbo.tProjectChargeRate' AS [__SourceTable], * FROM [dbo].[tProjectChargeRate];"
140,dbo,tProjectChargeRate_Welfare,FULL,2,"PRINT N'===== FULL: dbo.tProjectChargeRate_Welfare (2 rows) ====='; SELECT N'dbo.tProjectChargeRate_Welfare' AS [__SourceTable], * FROM [dbo].[tProjectChargeRate_Welfare];"
141,dbo,tProvince,FULL,77,"PRINT N'===== FULL: dbo.tProvince (77 rows) ====='; SELECT N'dbo.tProvince' AS [__SourceTable], * FROM [dbo].[tProvince];"
142,dbo,tPunishment,SAMPLE,1994,"PRINT N'===== SAMPLE: dbo.tPunishment (TOP 100 of 1994) ====='; SELECT TOP (100) N'dbo.tPunishment' AS [__SourceTable], * FROM [dbo].[tPunishment];"
143,dbo,tPunishmentStyle,FULL,3,"PRINT N'===== FULL: dbo.tPunishmentStyle (3 rows) ====='; SELECT N'dbo.tPunishmentStyle' AS [__SourceTable], * FROM [dbo].[tPunishmentStyle];"
144,dbo,tPUPInstallation,FULL,261,"PRINT N'===== FULL: dbo.tPUPInstallation (261 rows) ====='; SELECT N'dbo.tPUPInstallation' AS [__SourceTable], * FROM [dbo].[tPUPInstallation];"
145,dbo,tReimType,FULL,3,"PRINT N'===== FULL: dbo.tReimType (3 rows) ====='; SELECT N'dbo.tReimType' AS [__SourceTable], * FROM [dbo].[tReimType];"
146,dbo,tReport_name,FULL,134,"PRINT N'===== FULL: dbo.tReport_name (134 rows) ====='; SELECT N'dbo.tReport_name' AS [__SourceTable], * FROM [dbo].[tReport_name];"
147,dbo,tReportNormal_Config,FULL,46,"PRINT N'===== FULL: dbo.tReportNormal_Config (46 rows) ====='; SELECT N'dbo.tReportNormal_Config' AS [__SourceTable], * FROM [dbo].[tReportNormal_Config];"
148,dbo,tReportNormal_Language,FULL,46,"PRINT N'===== FULL: dbo.tReportNormal_Language (46 rows) ====='; SELECT N'dbo.tReportNormal_Language' AS [__SourceTable], * FROM [dbo].[tReportNormal_Language];"
149,dbo,tReportPayroll_FieldCaption,FULL,28,"PRINT N'===== FULL: dbo.tReportPayroll_FieldCaption (28 rows) ====='; SELECT N'dbo.tReportPayroll_FieldCaption' AS [__SourceTable], * FROM [dbo].[tReportPayroll_FieldCaption];"
150,dbo,tRequest,SAMPLE,7107,"PRINT N'===== SAMPLE: dbo.tRequest (TOP 100 of 7107) ====='; SELECT TOP (100) N'dbo.tRequest' AS [__SourceTable], * FROM [dbo].[tRequest];"
151,dbo,tRequest_byAdmin,SAMPLE,4074,"PRINT N'===== SAMPLE: dbo.tRequest_byAdmin (TOP 100 of 4074) ====='; SELECT TOP (100) N'dbo.tRequest_byAdmin' AS [__SourceTable], * FROM [dbo].[tRequest_byAdmin];"
152,dbo,tRequestSystem,FULL,8,"PRINT N'===== FULL: dbo.tRequestSystem (8 rows) ====='; SELECT N'dbo.tRequestSystem' AS [__SourceTable], * FROM [dbo].[tRequestSystem];"
153,dbo,tRequestType,FULL,43,"PRINT N'===== FULL: dbo.tRequestType (43 rows) ====='; SELECT N'dbo.tRequestType' AS [__SourceTable], * FROM [dbo].[tRequestType];"
154,dbo,tResignReason,SAMPLE,678,"PRINT N'===== SAMPLE: dbo.tResignReason (TOP 100 of 678) ====='; SELECT TOP (100) N'dbo.tResignReason' AS [__SourceTable], * FROM [dbo].[tResignReason];"
155,dbo,tRule,FULL,29,"PRINT N'===== FULL: dbo.tRule (29 rows) ====='; SELECT N'dbo.tRule' AS [__SourceTable], * FROM [dbo].[tRule];"
156,dbo,tSelectApprover,FULL,60,"PRINT N'===== FULL: dbo.tSelectApprover (60 rows) ====='; SELECT N'dbo.tSelectApprover' AS [__SourceTable], * FROM [dbo].[tSelectApprover];"
157,dbo,tSendMail_Process,SAMPLE,2790,"PRINT N'===== SAMPLE: dbo.tSendMail_Process (TOP 100 of 2790) ====='; SELECT TOP (100) N'dbo.tSendMail_Process' AS [__SourceTable], * FROM [dbo].[tSendMail_Process];"
158,dbo,tSetting_Email,FULL,1,"PRINT N'===== FULL: dbo.tSetting_Email (1 rows) ====='; SELECT N'dbo.tSetting_Email' AS [__SourceTable], * FROM [dbo].[tSetting_Email];"
159,dbo,tShift,FULL,7,"PRINT N'===== FULL: dbo.tShift (7 rows) ====='; SELECT N'dbo.tShift' AS [__SourceTable], * FROM [dbo].[tShift];"
160,dbo,tSiteTR,FULL,187,"PRINT N'===== FULL: dbo.tSiteTR (187 rows) ====='; SELECT N'dbo.tSiteTR' AS [__SourceTable], * FROM [dbo].[tSiteTR];"
161,dbo,tSlipStyle,FULL,5,"PRINT N'===== FULL: dbo.tSlipStyle (5 rows) ====='; SELECT N'dbo.tSlipStyle' AS [__SourceTable], * FROM [dbo].[tSlipStyle];"
162,dbo,tSSO_Account,FULL,3,"PRINT N'===== FULL: dbo.tSSO_Account (3 rows) ====='; SELECT N'dbo.tSSO_Account' AS [__SourceTable], * FROM [dbo].[tSSO_Account];"
163,dbo,tSSO_Data,FULL,1,"PRINT N'===== FULL: dbo.tSSO_Data (1 rows) ====='; SELECT N'dbo.tSSO_Data' AS [__SourceTable], * FROM [dbo].[tSSO_Data];"
164,dbo,tSSO_Hospital,FULL,27,"PRINT N'===== FULL: dbo.tSSO_Hospital (27 rows) ====='; SELECT N'dbo.tSSO_Hospital' AS [__SourceTable], * FROM [dbo].[tSSO_Hospital];"
165,dbo,tSSO_ResignReason,FULL,7,"PRINT N'===== FULL: dbo.tSSO_ResignReason (7 rows) ====='; SELECT N'dbo.tSSO_ResignReason' AS [__SourceTable], * FROM [dbo].[tSSO_ResignReason];"
166,dbo,tStage,SAMPLE,9568,"PRINT N'===== SAMPLE: dbo.tStage (TOP 100 of 9568) ====='; SELECT TOP (100) N'dbo.tStage' AS [__SourceTable], * FROM [dbo].[tStage];"
167,dbo,tSYS_LoadEmployeeDefault,FULL,1,"PRINT N'===== FULL: dbo.tSYS_LoadEmployeeDefault (1 rows) ====='; SELECT N'dbo.tSYS_LoadEmployeeDefault' AS [__SourceTable], * FROM [dbo].[tSYS_LoadEmployeeDefault];"
168,dbo,tSYS_MENU_MOD,FULL,4,"PRINT N'===== FULL: dbo.tSYS_MENU_MOD (4 rows) ====='; SELECT N'dbo.tSYS_MENU_MOD' AS [__SourceTable], * FROM [dbo].[tSYS_MENU_MOD];"
169,dbo,tSYS_RegistBank,FULL,12,"PRINT N'===== FULL: dbo.tSYS_RegistBank (12 rows) ====='; SELECT N'dbo.tSYS_RegistBank' AS [__SourceTable], * FROM [dbo].[tSYS_RegistBank];"
170,dbo,tSYS_WebMenu,FULL,126,"PRINT N'===== FULL: dbo.tSYS_WebMenu (126 rows) ====='; SELECT N'dbo.tSYS_WebMenu' AS [__SourceTable], * FROM [dbo].[tSYS_WebMenu];"
171,dbo,tSysConfig,FULL,6,"PRINT N'===== FULL: dbo.tSysConfig (6 rows) ====='; SELECT N'dbo.tSysConfig' AS [__SourceTable], * FROM [dbo].[tSysConfig];"
172,dbo,tSYSDayInMonth,FULL,31,"PRINT N'===== FULL: dbo.tSYSDayInMonth (31 rows) ====='; SELECT N'dbo.tSYSDayInMonth' AS [__SourceTable], * FROM [dbo].[tSYSDayInMonth];"
173,dbo,tSYSDownloadFileList,FULL,5,"PRINT N'===== FULL: dbo.tSYSDownloadFileList (5 rows) ====='; SELECT N'dbo.tSYSDownloadFileList' AS [__SourceTable], * FROM [dbo].[tSYSDownloadFileList];"
174,dbo,tSYSMODReportList,FULL,1,"PRINT N'===== FULL: dbo.tSYSMODReportList (1 rows) ====='; SELECT N'dbo.tSYSMODReportList' AS [__SourceTable], * FROM [dbo].[tSYSMODReportList];"
175,dbo,tSYSOutPayMenu,FULL,113,"PRINT N'===== FULL: dbo.tSYSOutPayMenu (113 rows) ====='; SELECT N'dbo.tSYSOutPayMenu' AS [__SourceTable], * FROM [dbo].[tSYSOutPayMenu];"
176,dbo,tSYSOutPayMenuAdvance,FULL,5,"PRINT N'===== FULL: dbo.tSYSOutPayMenuAdvance (5 rows) ====='; SELECT N'dbo.tSYSOutPayMenuAdvance' AS [__SourceTable], * FROM [dbo].[tSYSOutPayMenuAdvance];"
177,dbo,tSysParm,FULL,58,"PRINT N'===== FULL: dbo.tSysParm (58 rows) ====='; SELECT N'dbo.tSysParm' AS [__SourceTable], * FROM [dbo].[tSysParm];"
178,dbo,tSysSettings,FULL,2,"PRINT N'===== FULL: dbo.tSysSettings (2 rows) ====='; SELECT N'dbo.tSysSettings' AS [__SourceTable], * FROM [dbo].[tSysSettings];"
179,dbo,tSystem_CustomMenu,FULL,30,"PRINT N'===== FULL: dbo.tSystem_CustomMenu (30 rows) ====='; SELECT N'dbo.tSystem_CustomMenu' AS [__SourceTable], * FROM [dbo].[tSystem_CustomMenu];"
180,dbo,tSystem_Event,SAMPLE,19747,"PRINT N'===== SAMPLE: dbo.tSystem_Event (TOP 100 of 19747) ====='; SELECT TOP (100) N'dbo.tSystem_Event' AS [__SourceTable], * FROM [dbo].[tSystem_Event];"
181,dbo,tSystem_MEventName,FULL,9,"PRINT N'===== FULL: dbo.tSystem_MEventName (9 rows) ====='; SELECT N'dbo.tSystem_MEventName' AS [__SourceTable], * FROM [dbo].[tSystem_MEventName];"
182,dbo,tSYSTRMMenu,FULL,69,"PRINT N'===== FULL: dbo.tSYSTRMMenu (69 rows) ====='; SELECT N'dbo.tSYSTRMMenu' AS [__SourceTable], * FROM [dbo].[tSYSTRMMenu];"
183,dbo,tSYSTurnOverRate,FULL,8,"PRINT N'===== FULL: dbo.tSYSTurnOverRate (8 rows) ====='; SELECT N'dbo.tSYSTurnOverRate' AS [__SourceTable], * FROM [dbo].[tSYSTurnOverRate];"
184,dbo,tSYSUserRole,FULL,8,"PRINT N'===== FULL: dbo.tSYSUserRole (8 rows) ====='; SELECT N'dbo.tSYSUserRole' AS [__SourceTable], * FROM [dbo].[tSYSUserRole];"
185,dbo,tSysWeekName,FULL,7,"PRINT N'===== FULL: dbo.tSysWeekName (7 rows) ====='; SELECT N'dbo.tSysWeekName' AS [__SourceTable], * FROM [dbo].[tSysWeekName];"
186,dbo,tTax,FULL,8,"PRINT N'===== FULL: dbo.tTax (8 rows) ====='; SELECT N'dbo.tTax' AS [__SourceTable], * FROM [dbo].[tTax];"
187,dbo,tTAX_Data,FULL,1,"PRINT N'===== FULL: dbo.tTAX_Data (1 rows) ====='; SELECT N'dbo.tTAX_Data' AS [__SourceTable], * FROM [dbo].[tTAX_Data];"
188,dbo,tTax91,SAMPLE,22105,"PRINT N'===== SAMPLE: dbo.tTax91 (TOP 100 of 22105) ====='; SELECT TOP (100) N'dbo.tTax91' AS [__SourceTable], * FROM [dbo].[tTax91];"
189,dbo,tTaxRate,FULL,32,"PRINT N'===== FULL: dbo.tTaxRate (32 rows) ====='; SELECT N'dbo.tTaxRate' AS [__SourceTable], * FROM [dbo].[tTaxRate];"
190,dbo,tTemp_Access_AutoPushTime_MT,SAMPLE,52346,"PRINT N'===== SAMPLE: dbo.tTemp_Access_AutoPushTime_MT (TOP 100 of 52346) ====='; SELECT TOP (100) N'dbo.tTemp_Access_AutoPushTime_MT' AS [__SourceTable], * FROM [dbo].[tTemp_Access_AutoPushTime_MT];"
191,dbo,tTemp_AutoPushTime_I_T02_Reformatted,SAMPLE,24351,"PRINT N'===== SAMPLE: dbo.tTemp_AutoPushTime_I_T02_Reformatted (TOP 100 of 24351) ====='; SELECT TOP (100) N'dbo.tTemp_AutoPushTime_I_T02_Reformatted' AS [__SourceTable], * FROM [dbo].[tTemp_AutoPushTime_I_T02_Reformatted];"
192,dbo,tTemp_AutoPushTime_MT,SAMPLE,5717,"PRINT N'===== SAMPLE: dbo.tTemp_AutoPushTime_MT (TOP 100 of 5717) ====='; SELECT TOP (100) N'dbo.tTemp_AutoPushTime_MT' AS [__SourceTable], * FROM [dbo].[tTemp_AutoPushTime_MT];"
193,dbo,tTemp_COM100005450_SYN_01,FULL,1,"PRINT N'===== FULL: dbo.tTemp_COM100005450_SYN_01 (1 rows) ====='; SELECT N'dbo.tTemp_COM100005450_SYN_01' AS [__SourceTable], * FROM [dbo].[tTemp_COM100005450_SYN_01];"
194,dbo,tTemp_COM100006556_Incentive,FULL,1,"PRINT N'===== FULL: dbo.tTemp_COM100006556_Incentive (1 rows) ====='; SELECT N'dbo.tTemp_COM100006556_Incentive' AS [__SourceTable], * FROM [dbo].[tTemp_COM100006556_Incentive];"
195,dbo,tTemp_COM100006556_SYN_01,FULL,44,"PRINT N'===== FULL: dbo.tTemp_COM100006556_SYN_01 (44 rows) ====='; SELECT N'dbo.tTemp_COM100006556_SYN_01' AS [__SourceTable], * FROM [dbo].[tTemp_COM100006556_SYN_01];"
196,dbo,tTemp_COM1000080311_EmpExport,SAMPLE,5038,"PRINT N'===== SAMPLE: dbo.tTemp_COM1000080311_EmpExport (TOP 100 of 5038) ====='; SELECT TOP (100) N'dbo.tTemp_COM1000080311_EmpExport' AS [__SourceTable], * FROM [dbo].[tTemp_COM1000080311_EmpExport];"
197,dbo,tTemp_COM100009403_EmpExport,SAMPLE,2200,"PRINT N'===== SAMPLE: dbo.tTemp_COM100009403_EmpExport (TOP 100 of 2200) ====='; SELECT TOP (100) N'dbo.tTemp_COM100009403_EmpExport' AS [__SourceTable], * FROM [dbo].[tTemp_COM100009403_EmpExport];"
198,dbo,tTemp_COM100009403_I_T01,SAMPLE,700,"PRINT N'===== SAMPLE: dbo.tTemp_COM100009403_I_T01 (TOP 100 of 700) ====='; SELECT TOP (100) N'dbo.tTemp_COM100009403_I_T01' AS [__SourceTable], * FROM [dbo].[tTemp_COM100009403_I_T01];"
199,dbo,tTemp_COM100009403_SYN_01,FULL,1,"PRINT N'===== FULL: dbo.tTemp_COM100009403_SYN_01 (1 rows) ====='; SELECT N'dbo.tTemp_COM100009403_SYN_01' AS [__SourceTable], * FROM [dbo].[tTemp_COM100009403_SYN_01];"
200,dbo,tTemp_COM100009404_EmpExport,SAMPLE,4927,"PRINT N'===== SAMPLE: dbo.tTemp_COM100009404_EmpExport (TOP 100 of 4927) ====='; SELECT TOP (100) N'dbo.tTemp_COM100009404_EmpExport' AS [__SourceTable], * FROM [dbo].[tTemp_COM100009404_EmpExport];"
201,dbo,tTemp_COM100009404_I_T01,FULL,30,"PRINT N'===== FULL: dbo.tTemp_COM100009404_I_T01 (30 rows) ====='; SELECT N'dbo.tTemp_COM100009404_I_T01' AS [__SourceTable], * FROM [dbo].[tTemp_COM100009404_I_T01];"
202,dbo,tTemp_COM100009404_I_T01_Reformatted,FULL,30,"PRINT N'===== FULL: dbo.tTemp_COM100009404_I_T01_Reformatted (30 rows) ====='; SELECT N'dbo.tTemp_COM100009404_I_T01_Reformatted' AS [__SourceTable], * FROM [dbo].[tTemp_COM100009404_I_T01_Reformatted];"
203,dbo,tTemp_COM100009404_SYN_01,FULL,19,"PRINT N'===== FULL: dbo.tTemp_COM100009404_SYN_01 (19 rows) ====='; SELECT N'dbo.tTemp_COM100009404_SYN_01' AS [__SourceTable], * FROM [dbo].[tTemp_COM100009404_SYN_01];"
204,dbo,tTemp_COM1000114628_SYN_01,FULL,1,"PRINT N'===== FULL: dbo.tTemp_COM1000114628_SYN_01 (1 rows) ====='; SELECT N'dbo.tTemp_COM1000114628_SYN_01' AS [__SourceTable], * FROM [dbo].[tTemp_COM1000114628_SYN_01];"
205,dbo,tTemp_COM100011613_EmpExport,SAMPLE,4938,"PRINT N'===== SAMPLE: dbo.tTemp_COM100011613_EmpExport (TOP 100 of 4938) ====='; SELECT TOP (100) N'dbo.tTemp_COM100011613_EmpExport' AS [__SourceTable], * FROM [dbo].[tTemp_COM100011613_EmpExport];"
206,dbo,tTemp_COM100011613_I_T01,SAMPLE,700,"PRINT N'===== SAMPLE: dbo.tTemp_COM100011613_I_T01 (TOP 100 of 700) ====='; SELECT TOP (100) N'dbo.tTemp_COM100011613_I_T01' AS [__SourceTable], * FROM [dbo].[tTemp_COM100011613_I_T01];"
207,dbo,tTemp_COM100011613_I_T01_Reformatted,SAMPLE,700,"PRINT N'===== SAMPLE: dbo.tTemp_COM100011613_I_T01_Reformatted (TOP 100 of 700) ====='; SELECT TOP (100) N'dbo.tTemp_COM100011613_I_T01_Reformatted' AS [__SourceTable], * FROM [dbo].[tTemp_COM100011613_I_T01_Reformatted];"
208,dbo,tTemp_COM100011613_Incentive,FULL,1,"PRINT N'===== FULL: dbo.tTemp_COM100011613_Incentive (1 rows) ====='; SELECT N'dbo.tTemp_COM100011613_Incentive' AS [__SourceTable], * FROM [dbo].[tTemp_COM100011613_Incentive];"
209,dbo,tTemp_COM100011658_EmpExport,SAMPLE,1815,"PRINT N'===== SAMPLE: dbo.tTemp_COM100011658_EmpExport (TOP 100 of 1815) ====='; SELECT TOP (100) N'dbo.tTemp_COM100011658_EmpExport' AS [__SourceTable], * FROM [dbo].[tTemp_COM100011658_EmpExport];"
210,dbo,tTemp_COM100011658_SYN_01,FULL,1,"PRINT N'===== FULL: dbo.tTemp_COM100011658_SYN_01 (1 rows) ====='; SELECT N'dbo.tTemp_COM100011658_SYN_01' AS [__SourceTable], * FROM [dbo].[tTemp_COM100011658_SYN_01];"
211,dbo,tTemp_COM100012952_SYN_01,FULL,13,"PRINT N'===== FULL: dbo.tTemp_COM100012952_SYN_01 (13 rows) ====='; SELECT N'dbo.tTemp_COM100012952_SYN_01' AS [__SourceTable], * FROM [dbo].[tTemp_COM100012952_SYN_01];"
212,dbo,tTemp_COM1000129521_SYN_01,FULL,5,"PRINT N'===== FULL: dbo.tTemp_COM1000129521_SYN_01 (5 rows) ====='; SELECT N'dbo.tTemp_COM1000129521_SYN_01' AS [__SourceTable], * FROM [dbo].[tTemp_COM1000129521_SYN_01];"
213,dbo,tTemp_COM100014629_SYN_01,FULL,1,"PRINT N'===== FULL: dbo.tTemp_COM100014629_SYN_01 (1 rows) ====='; SELECT N'dbo.tTemp_COM100014629_SYN_01' AS [__SourceTable], * FROM [dbo].[tTemp_COM100014629_SYN_01];"
214,dbo,tTemp_COM133_EmpExport,SAMPLE,5045,"PRINT N'===== SAMPLE: dbo.tTemp_COM133_EmpExport (TOP 100 of 5045) ====='; SELECT TOP (100) N'dbo.tTemp_COM133_EmpExport' AS [__SourceTable], * FROM [dbo].[tTemp_COM133_EmpExport];"
215,dbo,tTemp_COM133_I_T01,FULL,374,"PRINT N'===== FULL: dbo.tTemp_COM133_I_T01 (374 rows) ====='; SELECT N'dbo.tTemp_COM133_I_T01' AS [__SourceTable], * FROM [dbo].[tTemp_COM133_I_T01];"
216,dbo,tTemp_COM133_I_T01_Reformatted,FULL,374,"PRINT N'===== FULL: dbo.tTemp_COM133_I_T01_Reformatted (374 rows) ====='; SELECT N'dbo.tTemp_COM133_I_T01_Reformatted' AS [__SourceTable], * FROM [dbo].[tTemp_COM133_I_T01_Reformatted];"
217,dbo,tTemp_COM133_Incentive,FULL,1,"PRINT N'===== FULL: dbo.tTemp_COM133_Incentive (1 rows) ====='; SELECT N'dbo.tTemp_COM133_Incentive' AS [__SourceTable], * FROM [dbo].[tTemp_COM133_Incentive];"
218,dbo,tTemp_COM133_SYN_01,FULL,13,"PRINT N'===== FULL: dbo.tTemp_COM133_SYN_01 (13 rows) ====='; SELECT N'dbo.tTemp_COM133_SYN_01' AS [__SourceTable], * FROM [dbo].[tTemp_COM133_SYN_01];"
219,dbo,tTemp_DESKTOPCPFG9DI_SYN_01,FULL,1,"PRINT N'===== FULL: dbo.tTemp_DESKTOPCPFG9DI_SYN_01 (1 rows) ====='; SELECT N'dbo.tTemp_DESKTOPCPFG9DI_SYN_01' AS [__SourceTable], * FROM [dbo].[tTemp_DESKTOPCPFG9DI_SYN_01];"
220,dbo,tTemp_ImportTime_SCC,SAMPLE,5717,"PRINT N'===== SAMPLE: dbo.tTemp_ImportTime_SCC (TOP 100 of 5717) ====='; SELECT TOP (100) N'dbo.tTemp_ImportTime_SCC' AS [__SourceTable], * FROM [dbo].[tTemp_ImportTime_SCC];"
221,dbo,tTemp_Khemchapasorn_SYN_01,FULL,1,"PRINT N'===== FULL: dbo.tTemp_Khemchapasorn_SYN_01 (1 rows) ====='; SELECT N'dbo.tTemp_Khemchapasorn_SYN_01' AS [__SourceTable], * FROM [dbo].[tTemp_Khemchapasorn_SYN_01];"
222,dbo,tTemp_Leave,SAMPLE,36101,"PRINT N'===== SAMPLE: dbo.tTemp_Leave (TOP 100 of 36101) ====='; SELECT TOP (100) N'dbo.tTemp_Leave' AS [__SourceTable], * FROM [dbo].[tTemp_Leave];"
223,dbo,tTemp_PICHA_EmpExport,FULL,1,"PRINT N'===== FULL: dbo.tTemp_PICHA_EmpExport (1 rows) ====='; SELECT N'dbo.tTemp_PICHA_EmpExport' AS [__SourceTable], * FROM [dbo].[tTemp_PICHA_EmpExport];"
224,dbo,tTemp_SCCDB01_I_T01,FULL,204,"PRINT N'===== FULL: dbo.tTemp_SCCDB01_I_T01 (204 rows) ====='; SELECT N'dbo.tTemp_SCCDB01_I_T01' AS [__SourceTable], * FROM [dbo].[tTemp_SCCDB01_I_T01];"
225,dbo,tTemp_SCCDB01_I_T01_Reformatted,FULL,204,"PRINT N'===== FULL: dbo.tTemp_SCCDB01_I_T01_Reformatted (204 rows) ====='; SELECT N'dbo.tTemp_SCCDB01_I_T01_Reformatted' AS [__SourceTable], * FROM [dbo].[tTemp_SCCDB01_I_T01_Reformatted];"
226,dbo,tTemp_SCCDB01_Incentive,FULL,1,"PRINT N'===== FULL: dbo.tTemp_SCCDB01_Incentive (1 rows) ====='; SELECT N'dbo.tTemp_SCCDB01_Incentive' AS [__SourceTable], * FROM [dbo].[tTemp_SCCDB01_Incentive];"
227,dbo,tTemp_SCCDB01_SYN_01,SAMPLE,15266,"PRINT N'===== SAMPLE: dbo.tTemp_SCCDB01_SYN_01 (TOP 100 of 15266) ====='; SELECT TOP (100) N'dbo.tTemp_SCCDB01_SYN_01' AS [__SourceTable], * FROM [dbo].[tTemp_SCCDB01_SYN_01];"
228,dbo,tTemp_SCCWEB01_I_T01,SAMPLE,516,"PRINT N'===== SAMPLE: dbo.tTemp_SCCWEB01_I_T01 (TOP 100 of 516) ====='; SELECT TOP (100) N'dbo.tTemp_SCCWEB01_I_T01' AS [__SourceTable], * FROM [dbo].[tTemp_SCCWEB01_I_T01];"
229,dbo,tTemp_SCCWEB01_I_T01_Reformatted,SAMPLE,516,"PRINT N'===== SAMPLE: dbo.tTemp_SCCWEB01_I_T01_Reformatted (TOP 100 of 516) ====='; SELECT TOP (100) N'dbo.tTemp_SCCWEB01_I_T01_Reformatted' AS [__SourceTable], * FROM [dbo].[tTemp_SCCWEB01_I_T01_Reformatted];"
230,dbo,tTemp_SCCWEB01_SYN_01,FULL,13,"PRINT N'===== FULL: dbo.tTemp_SCCWEB01_SYN_01 (13 rows) ====='; SELECT N'dbo.tTemp_SCCWEB01_SYN_01' AS [__SourceTable], * FROM [dbo].[tTemp_SCCWEB01_SYN_01];"
231,dbo,tTemp_SCCWIN10_EmpExport,FULL,21,"PRINT N'===== FULL: dbo.tTemp_SCCWIN10_EmpExport (21 rows) ====='; SELECT N'dbo.tTemp_SCCWIN10_EmpExport' AS [__SourceTable], * FROM [dbo].[tTemp_SCCWIN10_EmpExport];"
232,dbo,tTemp_SCCWIN10_SYN_01,FULL,15,"PRINT N'===== FULL: dbo.tTemp_SCCWIN10_SYN_01 (15 rows) ====='; SELECT N'dbo.tTemp_SCCWIN10_SYN_01' AS [__SourceTable], * FROM [dbo].[tTemp_SCCWIN10_SYN_01];"
233,dbo,tTemp_Timeinout_01,FULL,1,"PRINT N'===== FULL: dbo.tTemp_Timeinout_01 (1 rows) ====='; SELECT N'dbo.tTemp_Timeinout_01' AS [__SourceTable], * FROM [dbo].[tTemp_Timeinout_01];"
234,dbo,tTemp_Wanthida_SYN_01,FULL,1,"PRINT N'===== FULL: dbo.tTemp_Wanthida_SYN_01 (1 rows) ====='; SELECT N'dbo.tTemp_Wanthida_SYN_01' AS [__SourceTable], * FROM [dbo].[tTemp_Wanthida_SYN_01];"
235,dbo,tTemp_webadmin_SYN_01,FULL,1,"PRINT N'===== FULL: dbo.tTemp_webadmin_SYN_01 (1 rows) ====='; SELECT N'dbo.tTemp_webadmin_SYN_01' AS [__SourceTable], * FROM [dbo].[tTemp_webadmin_SYN_01];"
236,dbo,tTemp_WORAVUT_I_T01,FULL,454,"PRINT N'===== FULL: dbo.tTemp_WORAVUT_I_T01 (454 rows) ====='; SELECT N'dbo.tTemp_WORAVUT_I_T01' AS [__SourceTable], * FROM [dbo].[tTemp_WORAVUT_I_T01];"
237,dbo,tTemp_WORAVUT_I_T01_Reformatted,FULL,454,"PRINT N'===== FULL: dbo.tTemp_WORAVUT_I_T01_Reformatted (454 rows) ====='; SELECT N'dbo.tTemp_WORAVUT_I_T01_Reformatted' AS [__SourceTable], * FROM [dbo].[tTemp_WORAVUT_I_T01_Reformatted];"
238,dbo,tTemp_WORAVUT_SYN_01,FULL,15,"PRINT N'===== FULL: dbo.tTemp_WORAVUT_SYN_01 (15 rows) ====='; SELECT N'dbo.tTemp_WORAVUT_SYN_01' AS [__SourceTable], * FROM [dbo].[tTemp_WORAVUT_SYN_01];"
239,dbo,tTempBatch_TimeInOut,SAMPLE,75864,"PRINT N'===== SAMPLE: dbo.tTempBatch_TimeInOut (TOP 100 of 75864) ====='; SELECT TOP (100) N'dbo.tTempBatch_TimeInOut' AS [__SourceTable], * FROM [dbo].[tTempBatch_TimeInOut];"
240,dbo,tTempBatchEmp,SAMPLE,5039,"PRINT N'===== SAMPLE: dbo.tTempBatchEmp (TOP 100 of 5039) ====='; SELECT TOP (100) N'dbo.tTempBatchEmp' AS [__SourceTable], * FROM [dbo].[tTempBatchEmp];"
241,dbo,tTempBatchTime,SAMPLE,231794,"PRINT N'===== SAMPLE: dbo.tTempBatchTime (TOP 100 of 231794) ====='; SELECT TOP (100) N'dbo.tTempBatchTime' AS [__SourceTable], * FROM [dbo].[tTempBatchTime];"
242,dbo,tTimeCard_HideCol,FULL,1,"PRINT N'===== FULL: dbo.tTimeCard_HideCol (1 rows) ====='; SELECT N'dbo.tTimeCard_HideCol' AS [__SourceTable], * FROM [dbo].[tTimeCard_HideCol];"
243,dbo,tTimeInOut,SAMPLE,3551128,"PRINT N'===== SAMPLE: dbo.tTimeInOut (TOP 100 of 3551128) ====='; SELECT TOP (100) N'dbo.tTimeInOut' AS [__SourceTable], * FROM [dbo].[tTimeInOut];"
244,dbo,tTimeInOut_AddLeave,SAMPLE,726553,"PRINT N'===== SAMPLE: dbo.tTimeInOut_AddLeave (TOP 100 of 726553) ====='; SELECT TOP (100) N'dbo.tTimeInOut_AddLeave' AS [__SourceTable], * FROM [dbo].[tTimeInOut_AddLeave];"
245,dbo,tTimeInOut_ColDef,SAMPLE,635,"PRINT N'===== SAMPLE: dbo.tTimeInOut_ColDef (TOP 100 of 635) ====='; SELECT TOP (100) N'dbo.tTimeInOut_ColDef' AS [__SourceTable], * FROM [dbo].[tTimeInOut_ColDef];"
246,dbo,tTimeInOut_Data,SAMPLE,1420276,"PRINT N'===== SAMPLE: dbo.tTimeInOut_Data (TOP 100 of 1420276) ====='; SELECT TOP (100) N'dbo.tTimeInOut_Data' AS [__SourceTable], * FROM [dbo].[tTimeInOut_Data];"
247,dbo,tTimeInOut_FieldCaption,FULL,1,"PRINT N'===== FULL: dbo.tTimeInOut_FieldCaption (1 rows) ====='; SELECT N'dbo.tTimeInOut_FieldCaption' AS [__SourceTable], * FROM [dbo].[tTimeInOut_FieldCaption];"
248,dbo,tTimeInOut_RowName,FULL,6,"PRINT N'===== FULL: dbo.tTimeInOut_RowName (6 rows) ====='; SELECT N'dbo.tTimeInOut_RowName' AS [__SourceTable], * FROM [dbo].[tTimeInOut_RowName];"
249,dbo,tTimeInOut_T0xFormat,FULL,5,"PRINT N'===== FULL: dbo.tTimeInOut_T0xFormat (5 rows) ====='; SELECT N'dbo.tTimeInOut_T0xFormat' AS [__SourceTable], * FROM [dbo].[tTimeInOut_T0xFormat];"
250,dbo,tTimeStamp,SAMPLE,7377898,"PRINT N'===== SAMPLE: dbo.tTimeStamp (TOP 100 of 7377898) ====='; SELECT TOP (100) N'dbo.tTimeStamp' AS [__SourceTable], * FROM [dbo].[tTimeStamp];"
251,dbo,tTrainingCompany,FULL,1,"PRINT N'===== FULL: dbo.tTrainingCompany (1 rows) ====='; SELECT N'dbo.tTrainingCompany' AS [__SourceTable], * FROM [dbo].[tTrainingCompany];"
252,dbo,tTrainingType,FULL,7,"PRINT N'===== FULL: dbo.tTrainingType (7 rows) ====='; SELECT N'dbo.tTrainingType' AS [__SourceTable], * FROM [dbo].[tTrainingType];"
253,dbo,tUser,FULL,87,"PRINT N'===== FULL: dbo.tUser (87 rows) ====='; SELECT N'dbo.tUser' AS [__SourceTable], * FROM [dbo].[tUser];"
254,dbo,tUser_PWDHistory,FULL,109,"PRINT N'===== FULL: dbo.tUser_PWDHistory (109 rows) ====='; SELECT N'dbo.tUser_PWDHistory' AS [__SourceTable], * FROM [dbo].[tUser_PWDHistory];"
255,dbo,tUserGroup,FULL,7,"PRINT N'===== FULL: dbo.tUserGroup (7 rows) ====='; SELECT N'dbo.tUserGroup' AS [__SourceTable], * FROM [dbo].[tUserGroup];"
256,dbo,tUserWebTimeCardPermission,FULL,10,"PRINT N'===== FULL: dbo.tUserWebTimeCardPermission (10 rows) ====='; SELECT N'dbo.tUserWebTimeCardPermission' AS [__SourceTable], * FROM [dbo].[tUserWebTimeCardPermission];"
257,dbo,tUserWorkgroup,FULL,7,"PRINT N'===== FULL: dbo.tUserWorkgroup (7 rows) ====='; SELECT N'dbo.tUserWorkgroup' AS [__SourceTable], * FROM [dbo].[tUserWorkgroup];"
258,dbo,tvTimeAttendance_FieldCaption,FULL,100,"PRINT N'===== FULL: dbo.tvTimeAttendance_FieldCaption (100 rows) ====='; SELECT N'dbo.tvTimeAttendance_FieldCaption' AS [__SourceTable], * FROM [dbo].[tvTimeAttendance_FieldCaption];"
259,dbo,tW_Option,FULL,39,"PRINT N'===== FULL: dbo.tW_Option (39 rows) ====='; SELECT N'dbo.tW_Option' AS [__SourceTable], * FROM [dbo].[tW_Option];"
260,dbo,tWF_FieldCaption,FULL,1,"PRINT N'===== FULL: dbo.tWF_FieldCaption (1 rows) ====='; SELECT N'dbo.tWF_FieldCaption' AS [__SourceTable], * FROM [dbo].[tWF_FieldCaption];"
261,dbo,tWorkCalendar,FULL,3,"PRINT N'===== FULL: dbo.tWorkCalendar (3 rows) ====='; SELECT N'dbo.tWorkCalendar' AS [__SourceTable], * FROM [dbo].[tWorkCalendar];"
262,dbo,tWorkCalendarDetail,SAMPLE,945,"PRINT N'===== SAMPLE: dbo.tWorkCalendarDetail (TOP 100 of 945) ====='; SELECT TOP (100) N'dbo.tWorkCalendarDetail' AS [__SourceTable], * FROM [dbo].[tWorkCalendarDetail];"
263,dbo,tWorkCalendarDetailTemp,SAMPLE,3652,"PRINT N'===== SAMPLE: dbo.tWorkCalendarDetailTemp (TOP 100 of 3652) ====='; SELECT TOP (100) N'dbo.tWorkCalendarDetailTemp' AS [__SourceTable], * FROM [dbo].[tWorkCalendarDetailTemp];"
264,license,MASLicense,FULL,1,"PRINT N'===== FULL: license.MASLicense (1 rows) ====='; SELECT N'license.MASLicense' AS [__SourceTable], * FROM [license].[MASLicense];"
265,maspayroll,tPayroll_ColReport,FULL,260,"PRINT N'===== FULL: maspayroll.tPayroll_ColReport (260 rows) ====='; SELECT N'maspayroll.tPayroll_ColReport' AS [__SourceTable], * FROM [maspayroll].[tPayroll_ColReport];"
266,rosetta,Rosetta2_Conditions,FULL,6,"PRINT N'===== FULL: rosetta.Rosetta2_Conditions (6 rows) ====='; SELECT N'rosetta.Rosetta2_Conditions' AS [__SourceTable], * FROM [rosetta].[Rosetta2_Conditions];"
267,rosetta,Rosetta2_Operator,FULL,7,"PRINT N'===== FULL: rosetta.Rosetta2_Operator (7 rows) ====='; SELECT N'rosetta.Rosetta2_Operator' AS [__SourceTable], * FROM [rosetta].[Rosetta2_Operator];"
268,service,AppSyncConfig,SAMPLE,20793,"PRINT N'===== SAMPLE: service.AppSyncConfig (TOP 100 of 20793) ====='; SELECT TOP (100) N'service.AppSyncConfig' AS [__SourceTable], * FROM [service].[AppSyncConfig];"
269,service,EmployeeMappingID,SAMPLE,20686,"PRINT N'===== SAMPLE: service.EmployeeMappingID (TOP 100 of 20686) ====='; SELECT TOP (100) N'service.EmployeeMappingID' AS [__SourceTable], * FROM [service].[EmployeeMappingID];"
270,service,Log_PaySlip,SAMPLE,907,"PRINT N'===== SAMPLE: service.Log_PaySlip (TOP 100 of 907) ====='; SELECT TOP (100) N'service.Log_PaySlip' AS [__SourceTable], * FROM [service].[Log_PaySlip];"
271,service,Log_Registered,FULL,265,"PRINT N'===== FULL: service.Log_Registered (265 rows) ====='; SELECT N'service.Log_Registered' AS [__SourceTable], * FROM [service].[Log_Registered];"
272,service,PeriodSlip,FULL,186,"PRINT N'===== FULL: service.PeriodSlip (186 rows) ====='; SELECT N'service.PeriodSlip' AS [__SourceTable], * FROM [service].[PeriodSlip];"
273,service,Request,SAMPLE,629,"PRINT N'===== SAMPLE: service.Request (TOP 100 of 629) ====='; SELECT TOP (100) N'service.Request' AS [__SourceTable], * FROM [service].[Request];"
274,service,SysConfig,FULL,1,"PRINT N'===== FULL: service.SysConfig (1 rows) ====='; SELECT N'service.SysConfig' AS [__SourceTable], * FROM [service].[SysConfig];"
275,service,tAssignMobileFunction,FULL,3,"PRINT N'===== FULL: service.tAssignMobileFunction (3 rows) ====='; SELECT N'service.tAssignMobileFunction' AS [__SourceTable], * FROM [service].[tAssignMobileFunction];"
276,service,tTemp_LeaveApproved,FULL,78,"PRINT N'===== FULL: service.tTemp_LeaveApproved (78 rows) ====='; SELECT N'service.tTemp_LeaveApproved' AS [__SourceTable], * FROM [service].[tTemp_LeaveApproved];"
277,service,tTemp_LeaveBalance,SAMPLE,1708,"PRINT N'===== SAMPLE: service.tTemp_LeaveBalance (TOP 100 of 1708) ====='; SELECT TOP (100) N'service.tTemp_LeaveBalance' AS [__SourceTable], * FROM [service].[tTemp_LeaveBalance];"
278,service,tTemp_LeaveFlow,FULL,161,"PRINT N'===== FULL: service.tTemp_LeaveFlow (161 rows) ====='; SELECT N'service.tTemp_LeaveFlow' AS [__SourceTable], * FROM [service].[tTemp_LeaveFlow];"
279,service,tTemp_LeaveNonRequest,FULL,23,"PRINT N'===== FULL: service.tTemp_LeaveNonRequest (23 rows) ====='; SELECT N'service.tTemp_LeaveNonRequest' AS [__SourceTable], * FROM [service].[tTemp_LeaveNonRequest];"
280,service,tTemp_LeaveRequest,FULL,128,"PRINT N'===== FULL: service.tTemp_LeaveRequest (128 rows) ====='; SELECT N'service.tTemp_LeaveRequest' AS [__SourceTable], * FROM [service].[tTemp_LeaveRequest];"
281,service,tTemp_Leaves,SAMPLE,1193,"PRINT N'===== SAMPLE: service.tTemp_Leaves (TOP 100 of 1193) ====='; SELECT TOP (100) N'service.tTemp_Leaves' AS [__SourceTable], * FROM [service].[tTemp_Leaves];"
282,service,tTemp_LeaveTypes,FULL,21,"PRINT N'===== FULL: service.tTemp_LeaveTypes (21 rows) ====='; SELECT N'service.tTemp_LeaveTypes' AS [__SourceTable], * FROM [service].[tTemp_LeaveTypes];"
283,service,tTemp_OTApproved,SAMPLE,539,"PRINT N'===== SAMPLE: service.tTemp_OTApproved (TOP 100 of 539) ====='; SELECT TOP (100) N'service.tTemp_OTApproved' AS [__SourceTable], * FROM [service].[tTemp_OTApproved];"
284,service,tTemp_OTFlow,FULL,161,"PRINT N'===== FULL: service.tTemp_OTFlow (161 rows) ====='; SELECT N'service.tTemp_OTFlow' AS [__SourceTable], * FROM [service].[tTemp_OTFlow];"
285,service,tTemp_OTNonRequest,FULL,131,"PRINT N'===== FULL: service.tTemp_OTNonRequest (131 rows) ====='; SELECT N'service.tTemp_OTNonRequest' AS [__SourceTable], * FROM [service].[tTemp_OTNonRequest];"
286,service,tTemp_OTRequest,SAMPLE,813,"PRINT N'===== SAMPLE: service.tTemp_OTRequest (TOP 100 of 813) ====='; SELECT TOP (100) N'service.tTemp_OTRequest' AS [__SourceTable], * FROM [service].[tTemp_OTRequest];"
287,service,tTemp_Overtimes,SAMPLE,15154,"PRINT N'===== SAMPLE: service.tTemp_Overtimes (TOP 100 of 15154) ====='; SELECT TOP (100) N'service.tTemp_Overtimes' AS [__SourceTable], * FROM [service].[tTemp_Overtimes];"
288,service,tTemp_TimeAttendances,SAMPLE,17916,"PRINT N'===== SAMPLE: service.tTemp_TimeAttendances (TOP 100 of 17916) ====='; SELECT TOP (100) N'service.tTemp_TimeAttendances' AS [__SourceTable], * FROM [service].[tTemp_TimeAttendances];"
289,service,tTemp_TimeClocks,FULL,1,"PRINT N'===== FULL: service.tTemp_TimeClocks (1 rows) ====='; SELECT N'service.tTemp_TimeClocks' AS [__SourceTable], * FROM [service].[tTemp_TimeClocks];"
290,service,tTemp_WorkFlow,FULL,24,"PRINT N'===== FULL: service.tTemp_WorkFlow (24 rows) ====='; SELECT N'service.tTemp_WorkFlow' AS [__SourceTable], * FROM [service].[tTemp_WorkFlow];"
