erDiagram
    dbo_tEmployee ||--o{ dbo_tTimeStamp : "CardID -> EmployeeCode"
    dbo_tEmployee ||--o{ dbo_tTimeInOut : "EmployeeCode"
    dbo_tShift ||--o{ dbo_tTimeInOut : "SHF_ID"
    dbo_tEmployee ||--o{ dbo_tAssignShift : "EmployeeCode"
    dbo_tEmployee ||--o{ dbo_tAssignShiftByWeekDay : "EmployeeCode"
    dbo_tShift ||--o{ dbo_tShiftBreak : "SHF_ID"
    dbo_tShift ||--o{ dbo_tShiftLateIn : "SHF_ID"
    dbo_tShift ||--o{ dbo_tShiftLateOut : "SHF_ID"
    dbo_tShift ||--o{ dbo_tShiftOT : "SHF_ID"
    dbo_tWorkCalendar ||--o{ dbo_tWorkCalendarDetail : "WCD_ID"
    dbo_tCostCenter ||--o{ dbo_tTimeSheet_MultiPeriod : "CostCenter_ID"
    dbo_tShift ||--o{ dbo_tTimeSheet_MultiPeriod : "SHF_ID"
    dbo_tSiteTR ||--o{ dbo_tTimeSheet_MultiPeriod : "Site_ID"

    dbo_tTimeStamp {
      varchar CardID PK
      varchar Machine_ID PK
      varchar DateInput PK
      smallint nHour PK
      smallint nMinute PK
      varchar Duty PK
    }
    dbo_tTimeInOut {
      varchar EmployeeCode PK
      varchar DateStamp PK
      uniqueidentifier SHF_ID FK
    }
    dbo_tShift {
      uniqueidentifier SHF_ID PK
    }
