erDiagram
    dbo_tEmployee ||--o{ dbo_tApproverList : "EmployeeID -> EmployeeCode"
    dbo_tEmployee ||--o{ dbo_tAssignChargeRate : "EmployeeCode -> EmployeeCode"
    dbo_tUserGroup ||--o{ dbo_tAssignMenuPermission : "USG_ID -> USG_ID"
    dbo_tEmployee ||--o{ dbo_tAssignShift : "EmployeeCode -> EmployeeCode"
    dbo_tEmployee ||--o{ dbo_tAssignShiftByWeekDay : "EmployeeCode -> EmployeeCode"
    dbo_tUserGroup ||--o{ dbo_tAssignUserRole : "USG_ID -> USG_ID"
    dbo_tRule ||--o{ dbo_tCCList : "RuleID -> RuleID"
    dbo_tRule ||--o{ dbo_tCondition : "RuleID -> RuleID"
    dbo_tEmployeeTitle ||--o{ dbo_tEmployee : "EMPTT_ID -> EMPTT_ID"
    dbo_tSiteTR ||--o{ dbo_tEmployee : "Site_ID -> Site_ID"
    dbo_tRequestType ||--o{ dbo_tEmployeeLevel_LeaveType : "RequestTypeID -> RequestTypeID"
    dbo_tEmployee ||--o{ dbo_tEmployeePhoto : "EmployeeCode -> EmployeeCode"
    dbo_tEmployeeStatusGroup ||--o{ dbo_tEmployeeStatus : "EMPSTG_ID -> EMPSTG_ID"
    dbo_tEmployeeLevel_LeaveType ||--o{ dbo_tEmployeeWork_Quota : "EMPLLT_ID -> EMPLLT_ID"
    dbo_tRequestSystem ||--o{ dbo_tFlow : "RequestSystemID -> RequestSystemID"
    dbo_tRule ||--o{ dbo_tFlowPath : "RuleID -> RuleID"
    dbo_tImportPlan ||--o{ dbo_tImportPlan : "EmployeeCode -> EmployeeCode"
    dbo_tImportPlan ||--o{ dbo_tImportPlan : "DateStamp -> DateStamp"
    dbo_tEmployee ||--o{ dbo_tLOG_Payroll : "EmployeeCode -> EmployeeCode"
    dbo_tGroup ||--o{ dbo_tManager : "GroupID -> GroupID"
    dbo_tEmployee ||--o{ dbo_tManager_Delegated : "EmployeeCode -> EmployeeCode"
    dbo_tEmployee ||--o{ dbo_tPayroll : "EmployeeCode -> EmployeeCode"
    dbo_tPMPeriod ||--o{ dbo_tPayroll : "PMPERIOD_ID -> PMPeriod_ID"
    dbo_tProject ||--o{ dbo_tPMPeriod : "PRJ_ID -> PRJ_ID"
    dbo_tSSO_Account ||--o{ dbo_tProject : "SSOACC_ID -> SSOACC_ID"
    dbo_tEmployee ||--o{ dbo_tPunishment : "EmployeeCode -> EmployeeCode"
    dbo_tGUILTY_Type ||--o{ dbo_tPunishment : "GUILTY_TYPE_ID -> GUILTY_TYPE_ID"
    dbo_tReimType ||--o{ dbo_tReim : "REIM_TYPE_ID -> REIM_TYPE_ID"
    dbo_tReim ||--o{ dbo_tReimRef : "REIM_ID -> REIM_ID"
    dbo_tRule ||--o{ dbo_tRequest : "RuleID -> RuleID"
    dbo_tRequestSystem ||--o{ dbo_tRequestType : "RequestSystemID -> RequestSystemID"
    dbo_tEmployee ||--o{ dbo_tReward : "EmployeeCode -> EmployeeCode"
    dbo_tPERFORMANCE_Type ||--o{ dbo_tReward : "PERFORMANCE_TYPE_ID -> PERFORMANCE_TYPE_ID"
    dbo_tApproverList ||--o{ dbo_tSelectApprover : "APPLID -> APPLID"
    dbo_tFlowPath ||--o{ dbo_tSelectApprover : "FlowPathID -> FlowPathID"
    dbo_tShift ||--o{ dbo_tShiftBreak : "SHF_ID -> SHF_ID"
    dbo_tShift ||--o{ dbo_tShiftLateIn : "SHF_ID -> SHF_ID"
    dbo_tShift ||--o{ dbo_tShiftLateOut : "SHF_ID -> SHF_ID"
    dbo_tShift ||--o{ dbo_tShiftOT : "SHF_ID -> SHF_ID"
    dbo_tSiteUpdatePlan ||--o{ dbo_tSiteUpdate : "SiteUpdatePlanID -> ID"
    dbo_tSiteUpdatePlan ||--o{ dbo_tSiteUpdatePlan : "PredecessorID -> ID"
    dbo_tCompany ||--o{ dbo_tSSO_Account : "CPN_ID -> CPN_ID"
    dbo_tRequest ||--o{ dbo_tStage : "ReqID -> RequestID"
    dbo_tEmployee ||--o{ dbo_tTax91 : "EmployeeCode -> EmployeeCode"
    dbo_tEmployee ||--o{ dbo_tTimeInOut : "EmployeeCode -> EmployeeCode"
    dbo_tShift ||--o{ dbo_tTimeInOut : "SHF_ID -> SHF_ID"
    dbo_tCostCenter ||--o{ dbo_tTimeSheet_MultiPeriod : "CostCenter_ID -> CostCenter_ID"
    dbo_tShift ||--o{ dbo_tTimeSheet_MultiPeriod : "SHF_ID -> SHF_ID"
    dbo_tSiteTR ||--o{ dbo_tTimeSheet_MultiPeriod : "Site_ID -> Site_ID"
    dbo_tEmployee ||--o{ dbo_tTimeStamp : "CardID -> EmployeeCode"
    dbo_tGroup ||--o{ dbo_tUse_Flow : "GroupID -> GroupID"
    dbo_tApproverGroup ||--o{ dbo_tUseList : "APPGID -> APPGID"
    dbo_tUserGroup ||--o{ dbo_tUser : "USG_ID -> USG_ID"
    dbo_tUser ||--o{ dbo_tUser_LoginStat : "UID -> UID"
    dbo_tWorkCalendar ||--o{ dbo_tWorkCalendarDetail : "WCD_ID -> WCD_ID"
